name: "Dopamine: build, upload, release"

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    environment: Patch AutoBuildRelease
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid trustcache

      - name: Install Homebrew
        run: |
          set -x
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gnu-sed
          brew install make
          
      - name: Install THEOS (without SDKs)
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          cd $BASEDIR
         
      - name: Set Environment Variables
        run: |
         T8=$(TZ=UTC-8 date +'%Y%m%d_%H%M%S')
         TS=$(date -j -f "%Y%m%d_%H%M%S" "${T8}" +%s)
         SHASH=$(git rev-parse --short HEAD)
         echo "ctime=${T8}" >> $GITHUB_ENV
         echo "ctimestamp=${TS}" >> $GITHUB_ENV
         echo "shorthash=${SHASH}" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: |
         echo ${{ env.ctime }}
         echo ${{ env.ctimestamp }}
         echo ${{ env.shorthash }}
      - name: Build
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          sed -i '' "s/COMPILE_TIME=\`TZ=UTC-8 date \\\\\"+%Y%m%d_%H%M%S\\\\\"\`/COMPILE_TIME=${{ env.ctime }}/g" ./Dopamine/Makefile
          sed -i '' "s/GIT_COMMIT_HASH=\`git rev-parse --short HEAD\`/GIT_COMMIT_HASH=${{ env.shorthash }}/g" ./Dopamine/Makefile
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake
          cp Dopamine/Dopamine.tipa EnixDopamine.tipa
          mv Dopamine/Dopamine.tipa EnixDopamine_${{ env.ctime }}.tipa
 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.ctime }}
          name: "Dopamine: ${{ env.shorthash }}_${{ env.ctime }}"
      #    body_path: ./release.md
     #     token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa
